### ISSUE TITLE
Many Pipeline running errors (iGenomes, hisat index, then bbduk error)

### ISSUE THREAD

**Issue by dshechter** [nf-core/nascent#10] opened 2020-02-06 22:24 UTC
I've had many errors thrown when trying to run this pipeline (using docker). First, using igenome (e.g. --genome GRCh37) stops with this error: "No such variable: ch_fasta_for_hisat_index" (The output shows that it is using the correct S3 fasta file). I then added the --hisat_indices reference to downloaded hisat2 indices for grch37, but the pipeline still stopped with the same error. When I then changed the genome reference to --fasta and pointed to a GRCh37 fasta file, it ran, but stopped with this message:

> Error executing process > 'bbduk ([redacted].fastq)'
> 
> Caused by:
>   Missing output file(s) `*.trim.fastq` expected by process `bbduk ([redacted].fastq)`

and 
>  Set error histogram output to [redacted].ehist.txt
>   Exception in thread "main" java.lang.AssertionError: Can't find reference file /home/david/.nextflow/assets/nf-core/nascent/assets/adapters.fa
>         at jgi.BBDukF.<init>(BBDukF.java:556)
>   p: wheat jgi.BBDukF.main(BBDukF.java:67)

The file it can't find is indeed present in the assets folder. 

Finally, I tried adding the --saveAll flag, that didn't help. I'm now stuck. I'd really like to use this pipeline, I've used the RNAseq and chipseq nf-core pipelines and they are fantastic.

FastQC ran fine! The bbduk program is what's choking...

thanks

**Comment by ignaciot** [comment] 2020-02-06 23:03
Hi there,

Thanks for letting us know. Let's start with bbduck, which seems to be what's blocking you right now. Could you please paste here in a comment the complete list of arguments you're trying to run the pipeline with, so we can reproduce the issue and debug it?

**Comment by dshechter** [comment] 2020-02-07 00:56
Thanks for your quick response. Here's the initial command with the igenome and no hisat index:

> nextflow run nf-core/nascent --singleEnd --reads './fq/*.fastq.gz' -profile docker --genome GRCh37 --max_cpus 35

Here's the command that ran the pipeline and ended with the bbduck error:

> nextflow run nf-core/nascent --singleEnd --reads './fq/*.fastq.gz' -profile docker --fasta /data/NGS/Stds/hs/hg19/GRCh37.primary_assembly.genome.fasta --hisat_indices /data/NGS/Stds/hs/HISAT2_index/grch37/ --saveAll --max_cpus 35

**Comment by dshechter** [comment] 2020-02-07 21:18
Out of curiosity, I deleted all of the cached nextflow folders (e.g. ~/.nextflow) and everything except the fq in the pathway execution folder. It seems to be running now, currently building hisat indices (even though I gave it prebuilt files). Perhaps I had an earlier config file from another pipeline that caused trouble? I'll post a followup.

**Comment by ignaciot** [comment] 2020-02-07 21:22
Thanks for the update, I was actually trying to reproduce the error (unsuccessfully yet). 

I didn't realize you were running them all in the same location... I wonder if that is indeed the issue. The generated hisat2 indices are cached in the work directory, so if you deleted that directory it tries to rebuild them. I *just* noticed that you are using `--hisat_indices` as the argument, when it's actually `--hisat2_indices` (which is probably why it's rebuilding them since it didn't get anything for that other argument). Please let me know if that solved it!

**Comment by dshechter** [comment] 2020-02-07 21:27
This is on our local linux box. The nextflow installation was from a year or so ago, and systemwide. The 'assets' and config files are in the user home. The data and work directories are on a separate RAID, but I think nextflow keeps the pipelines and configs in that home folder. I didn't think it was an issue as we recently ran the nf-core/chipseq pipeline with no hiccup. Guess there was an old config file that caused trouble?

**Comment by ignaciot** [comment] 2020-02-07 22:15
I think I found the issue, and it's something I need to fix. The current script assumes the output of bbduk will follow the `*trim.fastq` which is bad form, because if the original fastq file is gzipped, so is the trimmed output. This should not be hardcoded this way and should depend on the input.

There are many updates and tweaks from [our lab's nascent transcription processing pipeline](https://github.com/Dowell-Lab/Nascent-Flow) that I haven't ported to the nf-core one yet, so this is a good opportunity to take care of it and push a new version. This particular problem, for example, is already addressed on that version. 

In the meantime, the (ugly as it can get) suggestion I have is to decompress the fastq files if viable. I will create a new branch to push out a new version with all these updates and bugfixes, but the test and review process can take some time, so using the uncompressed fastqs will be faster to get your analysis done.

**Comment by dshechter** [comment] 2020-02-07 22:38
Thanks - Small world, we're actually using data generated by arpeggio, this is a project with them. We're using their portal (and tfit calls), but wanted to do some independent analyses.  Your pipeline looks like it will add a lot more - will tfit and fstitch be included in the nf-core/nascent pipeline?

**Comment by ignaciot** [comment] 2020-02-07 22:46
Heh, the nascent transcription world is even smaller than I thought. I have no affiliation to Arpeggio, though (my thesis advisor does).  Yes, the idea is to also include tfit and fstitch, if we can put them in a container. Worst case, I can leave them as an optional flag and you install the tool/s locally.

**Comment by dshechter** [comment] 2020-02-10 03:09
I decompressed all the fastqs (named *.fastq and not *.fq) and tried again: failed immediately at bbduk. 

> Error executing process > 'bbduk [redacted]'
> 
> Caused by:
>   Missing output file(s) `*.trim.fastq` expected by process...

Similarly, it wouldn't work with the ---genome GRCh37 flag, even though the header "Genome Ref" pointed to the S3 bucket. The pipeline just stopped. There were two yellow warnings at the top:

> WARN: Access to undefined parameter `fasta` -- Initialise it to a default value eg. `params.fasta = some_value`
> WARN: Access to undefined parameter `readPaths` -- Initialise it to a default value eg. `params.readPaths = some_value`

I probably won't get back to this for a day or so, unfortunately may resort to doing everything by hand. I like using nextflow for the recordkeeping! I guess I could just use your lab's pipeline.

**Comment by ignaciot** [comment] 2020-02-10 05:00
One last thing to try (a suspicion I have because of that readPaths warning): You will find there's a dummy configuration used for unit testing (`conf/test.config`). What if, instead of passing the `--reads` argument, you change that file to list your SRRs in the specified format:

```readPaths = [
    ['SRRxxxxxx1', ['/path/to/the/SRRxxxxxx1.fastq']],
    ['SRRxxxxxx2', ['/path/to/the/SRRxxxxxx2.fastq']],
    [... etc]
]```

... and also update the `fasta = /path/to/you/genome.fa` entry. You can specify all other arguments here, too, like `max_cpus`, etc. Then, try invoking the pipeline using:

`nextflow run main.nf -profile test,docker`

(or, what I use to bypass docker permissions issues, `nextflow run main.nf -profile test,singularity`). I bet that will fix the issue... again, something else that will change in the updated version. If that doesn't work, you're welcome to try the lab one, which is what will essentially this one will become after merging the changes.

**Comment by dshechter** [comment] 2020-02-14 00:40
FYI I tried running _nextflow run nf-core/nascent -profile docker,test_ and it failed with the same bbduck error. I then tried it with _-profile conda,test_ instead of docker and the test ran fine! I think there is a problem with your docker container. We'll try it now with conda on our samples.

**Comment by dshechter** [comment] 2020-02-14 00:46
oh well, with our samples conda profile still failed at bbduk.

**Comment by ignaciot** [comment] 2020-02-14 17:33
That's really strange, I can't seem to reproduce the error here and I don't even have seqkit/bbduk installed so I know it's being pulled from the container. I am, however, using the `singularity` profile rather than `docker`, let me start up the docker daemon and try it to try reproducing that issue.

**Comment by dshechter** [comment] 2020-05-22 01:24
Hi - curious if you were able to update the pipeline. I'm coming back tot his project now - just set out to use the Dowell lab pipeline but the configurations are gong to take a while to play with. I'd also rather use the nf-core pipeline. Thanks for any update.

**Comment by ignaciot** [comment] 2020-05-22 04:57
Hey there,

Sorry, had to put this on the back burner for some time while working on my thesis defense (I passed this week!), but good timing for your message since this is next on my list. I have a major update ready, porting the changes over from the Dowell lab pipeline, but had some weird issue with the new production Docker container and the continuous integration tests. While I try to solve this over the next few days, you are welcome to check out my fork which will eventually become the 1.1 version of this pipeline:

https://github.com/ignaciot/nascent/tree/merging-template-updates

I'll post an update here once the issues have been resolved and the pipeline passes code review.

**Comment by dshechter** [comment] 2020-05-22 14:48
Congrats on your defense! I will check out your linked pipeline and see if it will run on our system.

**Comment by dshechter** [comment] 2022-01-28 18:12
Any followup on these issues? @ignaciot

**Comment by ignaciot** [comment] 2022-01-31 10:56
Still in the queue, unfortunately (too many things to juggle at the moment), but thanks to your reminder I'm currently looking for a collaborator to help maintain the pipeline and keep it up to date with the new nfcore templates.

**Comment by Emiller88** [comment] 2022-03-24 14:22
Closing this, as I think they've been addressed. @dshechter Give `dev` a shot if you're still interested!

**Closed by Emiller88** 2022-03-24 14:22 UTC
